[SPARK-41034][CONNECT][PYTHON][FOLLOW-UP] Fix mypy annotations test
### What changes were proposed in this pull request?
Fix python mypy

### Why are the changes needed?
https://github.com/apache/spark/pull/38541 breaks the linter

```
starting mypy annotations test...
annotations failed mypy checks:
python/pyspark/sql/connect/plan.py:683: error: Argument 1 to "plan" of "LogicalPlan" has incompatible type "Optional[RemoteSparkSession]"; expected "RemoteSparkSession"  [arg-type]
python/pyspark/sql/connect/plan.py:815: error: Argument 1 to "plan" of "LogicalPlan" has incompatible type "Optional[RemoteSparkSession]"; expected "RemoteSparkSession"  [arg-type]
Found 2 errors in 1 file (checked 369 source files)
1
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
local test

Closes #38597 from zhengruifeng/fix_py_lint_1.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>